### ISSUE TITLE
Linux Building

### ISSUE THREAD

**Issue by DaAwesomeP** [jpearman/convex#1]
Is building on Linux supported? I'm planning on using GItLab CI with a runner in Docker. I noticed that some of the pages in the documentation don't have instructions (or very vague ones at the very least) for how to install and build programs.

**Comment by jpearman** [comment]
Programs written using the ConVEX library can be compiled under linux.  If PROS (purdue robotics eclipse environment) has been installed then you can use the download tool supplied with that to send the compiled code to the cortex.

**Comment by DaAwesomeP** [comment]
If I want to build without Eclipse (using `make` from shell or bash only), then what are the dependencies?

**Comment by jpearman** [comment]
You don;t need eclipse, it's all makefile based.  You do need an ARM toolchain installed.  ChibiOS and ConVEX should be in the same folder.  See the getting started info here, linux should more or less be the same as using on OSX.
http://jpearman.github.io/convex/doxygen/html/getstarted.html

**Comment by DaAwesomeP** [comment]
Thank you. That should be good to get me started.

I'm yet to try anything yet, but in my own research I found this: https://launchpad.net/gcc-arm-embedded. It is compatible with the Cortex-M3 and is runs on Windows, OSX, and Linux. It's also actively developed and is open source.

**Comment by DaAwesomeP** [comment]
I was able to build the first example! I used the ARM Toolchain that I linked to in my above post. I used the included ChibiOS version 2.6.2. I originally tried to get it to work with Windows, but the toolchain did not include make, so I had to get MinGW at which point I remembered that I had a Lubuntu VM that would work just fine. It compiled without any errors and created the compiled HEX file. I also successfully build the cortex flash program for Linux (a simple `make` did it).

So, to compile for Linux you need:
- Your distribution's version of `build-essential`
- The arm toolchain, which on Ubuntu variants is the package `gcc-arm-none-eabi`
- GCC
- The cortex flasher program to make use of your code (build with `make` and install with `make install`)

My VM works well, and because it's Linux I'm using the real Make and GCC, and it's very fast. Thanks!

**Comment by DaAwesomeP** [comment]
I just got it to build using MinGW and `gcc-arm-none-eabi` on Windows, but it was _really_ slow compared to compiling in my Linux VM. I'm not sure what's causing this exactly, as MinGW is very optimized to be an official version of GCC and Make for Windows. It compiled about 2 files a second, while the Linux breezed through it very fast.

I guess I'll stick to compiling in Linux. I might flash it from Windows, but VirtualBox actually supports serial tunneling into the guest VM, so that should work well too.

**Comment by jpearman** [comment]
There's an issue with make under windows, something to do with case sensitive file names and dependancies.  See this vexforum post for more details.
http://www.vexforum.com/showpost.php?p=373342&postcount=245

**Comment by DaAwesomeP** [comment]
Well I don't have PROS nor Yargarto installed. I set a folder in my VM to be shared with Windows, and sure enough it built slowly too. So it definitely has to do with the Windows filesystem (NTFS being case insensitive). That csmake version was last updated in 2008, so I'll just stick to building on Linux with a case-sensitive filesystem (in this case ext4).

Thanks again for all of your help.
