### ISSUE TITLE
New ChibiOS version

### ISSUE THREAD

**Issue by DaAwesomeP** [jpearman/convex#2]
I've noticed that there is a [newer version of ChibiOS available](https://sourceforge.net/projects/chibios/files/ChibiOS_RT%20stable/). Will Convex work with the latest version?

**Comment by DaAwesomeP** [comment]
@jpearman Do you know of any incompatible differences between 2.x.x and 3.x.x?

**Comment by jpearman** [comment]
ConVEX will work with ChibiOS V2.6.8, however, there is a change needed in the Makefile if you want to use that version.  ConVEX is not compatible with ChibiOS V3.X, many changes were made in that version.  It could be ported but I don't have any plans to do that.

**Comment by DaAwesomeP** [comment]
I downloaded both v2.6.8 and 2.6.9 and adjusted the Makefile when testing both of them. Both of them produced this error during compilation:

``` make
bin/output.elf: 1: bin/output.elf: Syntax error: word unexpected (expecting ")")
../../../../ChibiOS_2.6.8/os/ports/GCC/ARMCMx/rules.mk:234: recipe for target 'bin/output.dmp' failed
make: *** [bin/output.dmp] Error 2
```

It does technically make a hex file, which is what I need to flash with, but this bug should probably be fixed.

**Comment by jpearman** [comment]
As I said above, you need to modify the makefile to include this line.

SZ   = $(TRGT)size

ChibiOS changed the rules.mk file in version 2.6.8 and gives an error if that is not defined, just add it to the makefile where the compiler settings are. I looked at the release notes for these more recent versions and there were not any changes that seemed relevant to the VEX cortex.  I specifically did not want to bother having to update the eclipse plugin as building and testing these always seems to be a real PITA.

**Comment by DaAwesomeP** [comment]
That worked!

I'm not using Eclipse, so that doesn't bother me. I just wanted to be sure that I was using the most recent ChibiOS possible. I don't know if they apply to the VEX, but there were a lot of bugfixes in the release notes.

Thanks for this fantastic library. I finally use the VEX on a professional level with legitimate C and a legitimate compilation process (yay for constructs and function pointers).
